from __future__ import annotations

from datetime import date, timedelta

from fastapi import APIRouter, Depends, Query
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.api.timefmt import iso_date, times
from app.models import OfficialWarning, Reservoir, ReservoirStatus
from app.services.database import get_db
from app.services.normalizer import utcnow

router = APIRouter()


@router.get("/reservoirs")
def reservoirs(
    on_date: date | None = Query(None, alias="date", description="YYYY-MM-DD (Asia/Bangkok); default latest"),
    size_class: str | None = Query(None, description="large | medium"),
    db: Session = Depends(get_db),
):
    """Latest (or given-date) status of each reservoir. Volumes MCM, flows MCM/day and m3/s."""
    if on_date is None:
        sub = (select(ReservoirStatus.reservoir_id, func.max(ReservoirStatus.observed_date).label("d"))
               .group_by(ReservoirStatus.reservoir_id).subquery())
        q = select(ReservoirStatus, Reservoir).join(
            sub, (ReservoirStatus.reservoir_id == sub.c.reservoir_id) & (ReservoirStatus.observed_date == sub.c.d))
    else:
        q = select(ReservoirStatus, Reservoir).where(ReservoirStatus.observed_date == on_date)
    q = q.join(Reservoir, Reservoir.id == ReservoirStatus.reservoir_id)
    if size_class:
        q = q.where(Reservoir.size_class == size_class)
    rows = db.execute(q.order_by(Reservoir.region, Reservoir.reservoir_code)).all()
    return {"reservoirs": [{
        "source": s.source, "reservoir_code": r.reservoir_code, "name_th": r.name_th, "name_en": r.name_en,
        "size_class": r.size_class, "region": r.region, "observed_date": iso_date(s.observed_date),
        "capacity_mcm": s.capacity_mcm, "storage_mcm": s.storage_mcm, "storage_pct": s.storage_pct,
        "usable_storage_mcm": s.usable_storage_mcm, "usable_storage_pct": s.usable_storage_pct,
        "inflow_mcm_day": s.inflow_mcm_day, "outflow_mcm_day": s.outflow_mcm_day,
        "inflow_m3s": s.inflow_m3s, "outflow_m3s": s.outflow_m3s,
        **times(ingested_at=s.ingested_at), "raw_payload_id": s.raw_payload_id,
    } for s, r in rows]}


@router.get("/warnings")
def warnings(
    since_hours: int = Query(72, ge=1, le=24 * 60),
    agency: str | None = None,
    warning_type: str | None = None,
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db),
):
    """Official warnings stored from source bulletins (not generated by this system)."""
    since = utcnow() - timedelta(hours=since_hours)
    q = select(OfficialWarning).where(
        func.coalesce(OfficialWarning.issued_at, OfficialWarning.ingested_at) >= since)
    if agency:
        q = q.where(OfficialWarning.agency == agency.upper())
    if warning_type:
        q = q.where(OfficialWarning.warning_type == warning_type)
    q = q.order_by(func.coalesce(OfficialWarning.issued_at, OfficialWarning.ingested_at).desc()).limit(limit)
    return {"warnings": [{
        "id": w.id, "source": w.source, "agency": w.agency, "source_warning_id": w.source_warning_id,
        "bulletin_header": w.bulletin_header, "warning_type": w.warning_type, "severity": w.severity,
        **times(issued_at=w.issued_at, effective_from=w.effective_from, effective_to=w.effective_to,
                ingested_at=w.ingested_at),
        "title": w.title, "body": w.body, "area_text": w.area_text, "province_codes": w.province_codes,
        "raw_payload_id": w.raw_payload_id,
    } for w in db.execute(q).scalars()]}
