"""phase 0 initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 04:24:25.566942
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_run',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('http_requests', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collector_run'))
    )
    op.create_index('ix_collector_run_job_started', 'collector_run', ['job', 'started_at'], unique=False)
    op.create_table('data_source_health',
    sa.Column('job', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('schema_verified', sa.Boolean(), nullable=False),
    sa.Column('expected_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_latency_ms', sa.Integer(), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('records_last_run', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('job', name=op.f('pk_data_source_health'))
    )
    op.create_index(op.f('ix_data_source_health_source'), 'data_source_health', ['source'], unique=False)
    op.create_geospatial_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_th', sa.String(length=128), nullable=True),
    sa.Column('province_code', sa.String(length=8), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('test_area', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location')),
    sa.UniqueConstraint('code', name=op.f('uq_location_code'))
    )
    op.create_geospatial_index('idx_location_geom', 'location', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_location_province_code'), 'location', ['province_code'], unique=False)
    op.create_table('raw_payload',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_key', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('same_as_id', sa.BigInteger(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parse_status', sa.String(length=32), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('records_parsed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['same_as_id'], ['raw_payload.id'], name=op.f('fk_raw_payload_same_as_id_raw_payload'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_payload'))
    )
    op.create_index('ix_raw_payload_checksum', 'raw_payload', ['checksum'], unique=False)
    op.create_index('ix_raw_payload_request_key_fetched', 'raw_payload', ['request_key', 'fetched_at'], unique=False)
    op.create_index('ix_raw_payload_source_dataset_fetched', 'raw_payload', ['source', 'dataset', 'fetched_at'], unique=False)
    op.create_geospatial_table('reservoir',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('reservoir_code', sa.String(length=64), nullable=False),
    sa.Column('name_th', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('size_class', sa.String(length=16), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('province_code', sa.String(length=8), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('capacity_mcm', sa.Float(), nullable=True),
    sa.Column('normal_high_storage_mcm', sa.Float(), nullable=True),
    sa.Column('min_storage_mcm', sa.Float(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservoir')),
    sa.UniqueConstraint('source', 'reservoir_code', name='uq_reservoir_source_code')
    )
    op.create_geospatial_index('idx_reservoir_geom', 'reservoir', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('water_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('station_code', sa.String(length=64), nullable=False),
    sa.Column('station_kind', sa.String(length=32), nullable=False),
    sa.Column('name_th', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('river_basin', sa.String(length=128), nullable=True),
    sa.Column('province_code', sa.String(length=8), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('ground_level_m', sa.Float(), nullable=True),
    sa.Column('bank_level_m', sa.Float(), nullable=True),
    sa.Column('warning_level_m', sa.Float(), nullable=True),
    sa.Column('critical_level_m', sa.Float(), nullable=True),
    sa.Column('datum', sa.String(length=32), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_water_station')),
    sa.UniqueConstraint('source', 'station_code', name='uq_water_station_source_code')
    )
    op.create_geospatial_index('idx_water_station_geom', 'water_station', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_water_station_province_code'), 'water_station', ['province_code'], unique=False)
    op.create_geospatial_table('weather_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('station_code', sa.String(length=64), nullable=False),
    sa.Column('wmo_id', sa.String(length=16), nullable=True),
    sa.Column('name_th', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('province_name', sa.String(length=128), nullable=True),
    sa.Column('province_code', sa.String(length=8), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_station')),
    sa.UniqueConstraint('source', 'station_code', name='uq_weather_station_source_code')
    )
    op.create_geospatial_index('idx_weather_station_geom', 'weather_station', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_weather_station_province_code'), 'weather_station', ['province_code'], unique=False)
    op.create_geospatial_table('flood_extent',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_feature_id', sa.String(length=128), nullable=False),
    sa.Column('product', sa.String(length=32), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sensor', sa.String(length=64), nullable=True),
    sa.Column('province_code', sa.String(length=8), nullable=True),
    sa.Column('province_name', sa.String(length=128), nullable=True),
    sa.Column('area_sqkm', sa.Float(), nullable=True),
    sa.Column('geometry', Geometry(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_payload_id', sa.BigInteger(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payload.id'], name=op.f('fk_flood_extent_raw_payload_id_raw_payload'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flood_extent')),
    sa.UniqueConstraint('source', 'source_feature_id', name='uq_flood_extent_key')
    )
    op.create_geospatial_index('idx_flood_extent_geometry', 'flood_extent', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_flood_extent_observed', 'flood_extent', ['observed_at'], unique=False)
    op.create_index(op.f('ix_flood_extent_province_code'), 'flood_extent', ['province_code'], unique=False)
    op.create_index(op.f('ix_flood_extent_raw_payload_id'), 'flood_extent', ['raw_payload_id'], unique=False)
    op.create_index(op.f('ix_flood_extent_source'), 'flood_extent', ['source'], unique=False)
    op.create_table('flood_point_check',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('is_flooded', sa.Boolean(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_payload_id', sa.BigInteger(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_flood_point_check_location_id_location')),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payload.id'], name=op.f('fk_flood_point_check_raw_payload_id_raw_payload'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flood_point_check')),
    sa.UniqueConstraint('source', 'location_id', 'checked_at', name='uq_flood_point_check_key')
    )
    op.create_index(op.f('ix_flood_point_check_raw_payload_id'), 'flood_point_check', ['raw_payload_id'], unique=False)
    op.create_index(op.f('ix_flood_point_check_source'), 'flood_point_check', ['source'], unique=False)
    op.create_table('forecast_run',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('model_run_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temporal_resolution_seconds', sa.Integer(), nullable=True),
    sa.Column('meta_raw_payload_id', sa.BigInteger(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['meta_raw_payload_id'], ['raw_payload.id'], name=op.f('fk_forecast_run_meta_raw_payload_id_raw_payload'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_run')),
    sa.UniqueConstraint('source', 'model', 'model_run_time', name='uq_forecast_run_key')
    )
    op.create_table('official_warning',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('agency', sa.String(length=32), nullable=False),
    sa.Column('source_warning_id', sa.String(length=128), nullable=False),
    sa.Column('bulletin_header', sa.String(length=128), nullable=True),
    sa.Column('warning_type', sa.String(length=64), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('area_text', sa.Text(), nullable=True),
    sa.Column('province_codes', postgresql.ARRAY(sa.String(length=8)), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_payload_id', sa.BigInteger(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payload.id'], name=op.f('fk_official_warning_raw_payload_id_raw_payload'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_official_warning')),
    sa.UniqueConstraint('source', 'source_warning_id', name='uq_official_warning_key')
    )
    op.create_index('ix_official_warning_issued', 'official_warning', ['issued_at'], unique=False)
    op.create_index(op.f('ix_official_warning_raw_payload_id'), 'official_warning', ['raw_payload_id'], unique=False)
    op.create_index(op.f('ix_official_warning_source'), 'official_warning', ['source'], unique=False)
    op.create_table('reservoir_status',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('reservoir_id', sa.Integer(), nullable=False),
    sa.Column('observed_date', sa.Date(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('storage_mcm', sa.Float(), nullable=True),
    sa.Column('storage_pct', sa.Float(), nullable=True),
    sa.Column('usable_storage_mcm', sa.Float(), nullable=True),
    sa.Column('usable_storage_pct', sa.Float(), nullable=True),
    sa.Column('inflow_mcm_day', sa.Float(), nullable=True),
    sa.Column('outflow_mcm_day', sa.Float(), nullable=True),
    sa.Column('inflow_m3s', sa.Float(), nullable=True),
    sa.Column('outflow_m3s', sa.Float(), nullable=True),
    sa.Column('capacity_mcm', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_payload_id', sa.BigInteger(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payload.id'], name=op.f('fk_reservoir_status_raw_payload_id_raw_payload'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservoir_id'], ['reservoir.id'], name=op.f('fk_reservoir_status_reservoir_id_reservoir')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservoir_status')),
    sa.UniqueConstraint('source', 'reservoir_id', 'observed_date', name='uq_reservoir_status_key')
    )
    op.create_index(op.f('ix_reservoir_status_raw_payload_id'), 'reservoir_status', ['raw_payload_id'], unique=False)
    op.create_index('ix_reservoir_status_res_date', 'reservoir_status', ['reservoir_id', 'observed_date'], unique=False)
    op.create_index(op.f('ix_reservoir_status_source'), 'reservoir_status', ['source'], unique=False)
    op.create_table('water_level_observation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('water_level_m', sa.Float(), nullable=True),
    sa.Column('discharge_m3s', sa.Float(), nullable=True),
    sa.Column('rain_mm', sa.Float(), nullable=True),
    sa.Column('rain_period_hours', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_payload_id', sa.BigInteger(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payload.id'], name=op.f('fk_water_level_observation_raw_payload_id_raw_payload'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['water_station.id'], name=op.f('fk_water_level_observation_station_id_water_station')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_water_level_observation')),
    sa.UniqueConstraint('source', 'station_id', 'observed_at', name='uq_water_level_observation_key')
    )
    op.create_index(op.f('ix_water_level_observation_raw_payload_id'), 'water_level_observation', ['raw_payload_id'], unique=False)
    op.create_index(op.f('ix_water_level_observation_source'), 'water_level_observation', ['source'], unique=False)
    op.create_index('ix_water_level_observation_station_time', 'water_level_observation', ['station_id', 'observed_at'], unique=False)
    op.create_table('weather_observation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('obs_type', sa.String(length=32), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('dew_point_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('pressure_msl_hpa', sa.Float(), nullable=True),
    sa.Column('station_pressure_hpa', sa.Float(), nullable=True),
    sa.Column('visibility_km', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('cloud_cover_okta', sa.Float(), nullable=True),
    sa.Column('rain_mm', sa.Float(), nullable=True),
    sa.Column('rain_period_hours', sa.Float(), nullable=True),
    sa.Column('rain_24h_mm', sa.Float(), nullable=True),
    sa.Column('max_temperature_c', sa.Float(), nullable=True),
    sa.Column('min_temperature_c', sa.Float(), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_payload_id', sa.BigInteger(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payload.id'], name=op.f('fk_weather_observation_raw_payload_id_raw_payload'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['weather_station.id'], name=op.f('fk_weather_observation_station_id_weather_station')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_observation')),
    sa.UniqueConstraint('source', 'station_id', 'observed_at', 'obs_type', name='uq_weather_observation_key')
    )
    op.create_index(op.f('ix_weather_observation_raw_payload_id'), 'weather_observation', ['raw_payload_id'], unique=False)
    op.create_index(op.f('ix_weather_observation_source'), 'weather_observation', ['source'], unique=False)
    op.create_index('ix_weather_observation_station_time', 'weather_observation', ['station_id', 'observed_at'], unique=False)
    op.create_table('weather_forecast',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('product', sa.String(length=32), nullable=False),
    sa.Column('forecast_run_id', sa.BigInteger(), nullable=True),
    sa.Column('model_run_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forecast_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lead_time_hours', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('grid_lat', sa.Float(), nullable=True),
    sa.Column('grid_lon', sa.Float(), nullable=True),
    sa.Column('grid_elevation_m', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('rain_mm', sa.Float(), nullable=True),
    sa.Column('precip_probability_pct', sa.Float(), nullable=True),
    sa.Column('pressure_msl_hpa', sa.Float(), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('wind_gust_kmh', sa.Float(), nullable=True),
    sa.Column('soil_moisture_m3m3', sa.Float(), nullable=True),
    sa.Column('soil_moisture_layer', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_payload_id', sa.BigInteger(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_run.id'], name=op.f('fk_weather_forecast_forecast_run_id_forecast_run'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_weather_forecast_location_id_location')),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payload.id'], name=op.f('fk_weather_forecast_raw_payload_id_raw_payload'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_forecast')),
    sa.UniqueConstraint('source', 'model', 'product', 'model_run_time', 'forecast_time', 'location_id', name='uq_weather_forecast_key', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_weather_forecast_forecast_run_id'), 'weather_forecast', ['forecast_run_id'], unique=False)
    op.create_index('ix_weather_forecast_lookup', 'weather_forecast', ['location_id', 'model', 'forecast_time'], unique=False)
    op.create_index(op.f('ix_weather_forecast_raw_payload_id'), 'weather_forecast', ['raw_payload_id'], unique=False)
    op.create_index(op.f('ix_weather_forecast_source'), 'weather_forecast', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_forecast_source'), table_name='weather_forecast')
    op.drop_index(op.f('ix_weather_forecast_raw_payload_id'), table_name='weather_forecast')
    op.drop_index('ix_weather_forecast_lookup', table_name='weather_forecast')
    op.drop_index(op.f('ix_weather_forecast_forecast_run_id'), table_name='weather_forecast')
    op.drop_table('weather_forecast')
    op.drop_index('ix_weather_observation_station_time', table_name='weather_observation')
    op.drop_index(op.f('ix_weather_observation_source'), table_name='weather_observation')
    op.drop_index(op.f('ix_weather_observation_raw_payload_id'), table_name='weather_observation')
    op.drop_table('weather_observation')
    op.drop_index('ix_water_level_observation_station_time', table_name='water_level_observation')
    op.drop_index(op.f('ix_water_level_observation_source'), table_name='water_level_observation')
    op.drop_index(op.f('ix_water_level_observation_raw_payload_id'), table_name='water_level_observation')
    op.drop_table('water_level_observation')
    op.drop_index(op.f('ix_reservoir_status_source'), table_name='reservoir_status')
    op.drop_index('ix_reservoir_status_res_date', table_name='reservoir_status')
    op.drop_index(op.f('ix_reservoir_status_raw_payload_id'), table_name='reservoir_status')
    op.drop_table('reservoir_status')
    op.drop_index(op.f('ix_official_warning_source'), table_name='official_warning')
    op.drop_index(op.f('ix_official_warning_raw_payload_id'), table_name='official_warning')
    op.drop_index('ix_official_warning_issued', table_name='official_warning')
    op.drop_table('official_warning')
    op.drop_table('forecast_run')
    op.drop_index(op.f('ix_flood_point_check_source'), table_name='flood_point_check')
    op.drop_index(op.f('ix_flood_point_check_raw_payload_id'), table_name='flood_point_check')
    op.drop_table('flood_point_check')
    op.drop_index(op.f('ix_flood_extent_source'), table_name='flood_extent')
    op.drop_index(op.f('ix_flood_extent_raw_payload_id'), table_name='flood_extent')
    op.drop_index(op.f('ix_flood_extent_province_code'), table_name='flood_extent')
    op.drop_index('ix_flood_extent_observed', table_name='flood_extent')
    op.drop_geospatial_index('idx_flood_extent_geometry', table_name='flood_extent', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('flood_extent')
    op.drop_index(op.f('ix_weather_station_province_code'), table_name='weather_station')
    op.drop_geospatial_index('idx_weather_station_geom', table_name='weather_station', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('weather_station')
    op.drop_index(op.f('ix_water_station_province_code'), table_name='water_station')
    op.drop_geospatial_index('idx_water_station_geom', table_name='water_station', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('water_station')
    op.drop_geospatial_index('idx_reservoir_geom', table_name='reservoir', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('reservoir')
    op.drop_index('ix_raw_payload_source_dataset_fetched', table_name='raw_payload')
    op.drop_index('ix_raw_payload_request_key_fetched', table_name='raw_payload')
    op.drop_index('ix_raw_payload_checksum', table_name='raw_payload')
    op.drop_table('raw_payload')
    op.drop_index(op.f('ix_location_province_code'), table_name='location')
    op.drop_geospatial_index('idx_location_geom', table_name='location', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('location')
    op.drop_index(op.f('ix_data_source_health_source'), table_name='data_source_health')
    op.drop_table('data_source_health')
    op.drop_index('ix_collector_run_job_started', table_name='collector_run')
    op.drop_table('collector_run')
    # ### end Alembic commands ###
