"""dashboard api support: source water fields, reservoir storage split, prepared forecast vars

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 05:32:15.095419
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('kind', sa.String(length=32), server_default='forecast_point', nullable=False))
    op.add_column('reservoir_status', sa.Column('normal_storage_mcm', sa.Float(), nullable=True))
    op.add_column('reservoir_status', sa.Column('dead_storage_mcm', sa.Float(), nullable=True))
    op.add_column('water_level_observation', sa.Column('rain_1h_mm', sa.Float(), nullable=True))
    op.add_column('water_level_observation', sa.Column('source_prev_level_m', sa.Float(), nullable=True))
    op.add_column('water_level_observation', sa.Column('source_diff_to_bank_m', sa.Float(), nullable=True))
    op.add_column('water_level_observation', sa.Column('source_diff_to_bank_text', sa.String(length=64), nullable=True))
    op.add_column('water_level_observation', sa.Column('source_situation_level', sa.Integer(), nullable=True))
    op.add_column('weather_forecast', sa.Column('cape_jkg', sa.Float(), nullable=True))
    op.add_column('weather_forecast', sa.Column('visibility_m', sa.Float(), nullable=True))
    op.add_column('weather_forecast', sa.Column('runoff_mm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_forecast', 'runoff_mm')
    op.drop_column('weather_forecast', 'visibility_m')
    op.drop_column('weather_forecast', 'cape_jkg')
    op.drop_column('water_level_observation', 'source_situation_level')
    op.drop_column('water_level_observation', 'source_diff_to_bank_text')
    op.drop_column('water_level_observation', 'source_diff_to_bank_m')
    op.drop_column('water_level_observation', 'source_prev_level_m')
    op.drop_column('water_level_observation', 'rain_1h_mm')
    op.drop_column('reservoir_status', 'dead_storage_mcm')
    op.drop_column('reservoir_status', 'normal_storage_mcm')
    op.drop_column('location', 'kind')
    # ### end Alembic commands ###
