"""terrain: dem_tile, terrain_profile, waterway

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-28 06:27:10.879633
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dem_tile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset', sa.String(length=32), nullable=False),
    sa.Column('tile_id', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('source_member', sa.String(length=128), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('nodata', sa.Float(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dem_tile')),
    sa.UniqueConstraint('dataset', 'tile_id', name='uq_dem_tile_dataset_tile')
    )
    op.create_geospatial_table('terrain_profile',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_code', sa.String(length=96), nullable=False),
    sa.Column('dataset', sa.String(length=32), nullable=False),
    sa.Column('method_version', sa.String(length=16), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('rel_elev_250_m', sa.Float(), nullable=True),
    sa.Column('rel_elev_500_m', sa.Float(), nullable=True),
    sa.Column('rel_elev_1000_m', sa.Float(), nullable=True),
    sa.Column('slope_deg', sa.Float(), nullable=True),
    sa.Column('terrain_position', sa.String(length=16), nullable=True),
    sa.Column('possible_local_depression', sa.Boolean(), nullable=True),
    sa.Column('depression_depth_m', sa.Float(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terrain_profile')),
    sa.UniqueConstraint('subject_type', 'subject_code', 'dataset', 'method_version', name='uq_terrain_profile_key')
    )
    op.create_geospatial_index('idx_terrain_profile_geom', 'terrain_profile', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('waterway',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('osm_type', sa.String(length=16), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('waterway_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTILINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source_snapshot', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waterway')),
    sa.UniqueConstraint('source', 'osm_type', 'osm_id', name='uq_waterway_source_osm')
    )
    op.create_geospatial_index('idx_waterway_geom', 'waterway', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_waterway_type', 'waterway', ['waterway_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waterway_type', table_name='waterway')
    op.drop_geospatial_index('idx_waterway_geom', table_name='waterway', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('waterway')
    op.drop_geospatial_index('idx_terrain_profile_geom', table_name='terrain_profile', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('terrain_profile')
    op.drop_table('dem_tile')
    # ### end Alembic commands ###
