"""hydro: basins, rivers, station links/relations, training

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-28 06:49:35.352066
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('hydro_basin',
    sa.Column('hybas_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('next_down', sa.BigInteger(), nullable=False),
    sa.Column('next_sink', sa.BigInteger(), nullable=True),
    sa.Column('main_bas', sa.BigInteger(), nullable=True),
    sa.Column('pfaf_id', sa.BigInteger(), nullable=True),
    sa.Column('sub_area_km2', sa.Float(), nullable=True),
    sa.Column('up_area_km2', sa.Float(), nullable=True),
    sa.Column('dist_main_km', sa.Float(), nullable=True),
    sa.Column('coast', sa.SmallInteger(), nullable=True),
    sa.Column('endo', sa.SmallInteger(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source_version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('hybas_id', name=op.f('pk_hydro_basin'))
    )
    op.create_geospatial_index('idx_hydro_basin_geom', 'hydro_basin', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_hydro_basin_level_next_down', 'hydro_basin', ['level', 'next_down'], unique=False)
    op.create_geospatial_table('hydro_river',
    sa.Column('hyriv_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('next_down', sa.BigInteger(), nullable=False),
    sa.Column('main_riv', sa.BigInteger(), nullable=True),
    sa.Column('length_km', sa.Float(), nullable=True),
    sa.Column('dist_dn_km', sa.Float(), nullable=True),
    sa.Column('dist_up_km', sa.Float(), nullable=True),
    sa.Column('catch_km2', sa.Float(), nullable=True),
    sa.Column('upland_km2', sa.Float(), nullable=True),
    sa.Column('dis_av_cms', sa.Float(), nullable=True),
    sa.Column('ord_stra', sa.SmallInteger(), nullable=True),
    sa.Column('ord_clas', sa.SmallInteger(), nullable=True),
    sa.Column('hybas_l12', sa.BigInteger(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTILINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source_version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('hyriv_id', name=op.f('pk_hydro_river'))
    )
    op.create_geospatial_index('idx_hydro_river_geom', 'hydro_river', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_hydro_river_hybas_l12'), 'hydro_river', ['hybas_l12'], unique=False)
    op.create_index(op.f('ix_hydro_river_main_riv'), 'hydro_river', ['main_riv'], unique=False)
    op.create_index(op.f('ix_hydro_river_next_down'), 'hydro_river', ['next_down'], unique=False)
    op.create_table('static_source_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('source_member', sa.String(length=256), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_static_source_file')),
    sa.UniqueConstraint('dataset', 'name', name='uq_static_source_file_dataset_name')
    )
    op.create_table('station_hydro_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('method_version', sa.String(length=16), nullable=False),
    sa.Column('hyriv_id', sa.BigInteger(), nullable=True),
    sa.Column('reach_distance_m', sa.Float(), nullable=True),
    sa.Column('reach_upland_km2', sa.Float(), nullable=True),
    sa.Column('reach_method', sa.String(length=24), nullable=False),
    sa.Column('hybas_l12', sa.BigInteger(), nullable=True),
    sa.Column('osm_waterway_name', sa.String(length=255), nullable=True),
    sa.Column('osm_waterway_distance_m', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['water_station.id'], name=op.f('fk_station_hydro_link_station_id_water_station'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_station_hydro_link')),
    sa.UniqueConstraint('station_id', 'method_version', name='uq_station_hydro_link_station')
    )
    op.create_table('station_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('other_station_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=16), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('river_distance_km', sa.Float(), nullable=True),
    sa.Column('hops', sa.Integer(), nullable=True),
    sa.Column('same_river_name', sa.Boolean(), nullable=True),
    sa.Column('lag_hours', sa.Float(), nullable=True),
    sa.Column('lag_basis', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('method_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['other_station_id'], ['water_station.id'], name=op.f('fk_station_relation_other_station_id_water_station'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['water_station.id'], name=op.f('fk_station_relation_station_id_water_station'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_station_relation')),
    sa.UniqueConstraint('station_id', 'other_station_id', 'network', name='uq_station_relation_pair')
    )
    op.create_index('ix_station_relation_station', 'station_relation', ['station_id', 'relation'], unique=False)
    op.create_table('water_forecast_training',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('prediction_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_hours', sa.SmallInteger(), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_version', sa.String(length=16), nullable=False),
    sa.Column('current_level_m', sa.Float(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rain_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upstream_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('terrain_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_water_level_m', sa.Float(), nullable=True),
    sa.Column('actual_change_m', sa.Float(), nullable=True),
    sa.Column('actual_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('labelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['water_station.id'], name=op.f('fk_water_forecast_training_station_id_water_station'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_water_forecast_training')),
    sa.UniqueConstraint('station_id', 'prediction_time', 'horizon_hours', name='uq_water_forecast_training_key')
    )
    op.create_index('ix_water_forecast_training_target_unlabelled', 'water_forecast_training', ['target_time', 'labelled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_water_forecast_training_target_unlabelled', table_name='water_forecast_training')
    op.drop_table('water_forecast_training')
    op.drop_index('ix_station_relation_station', table_name='station_relation')
    op.drop_table('station_relation')
    op.drop_table('station_hydro_link')
    op.drop_table('static_source_file')
    op.drop_index(op.f('ix_hydro_river_next_down'), table_name='hydro_river')
    op.drop_index(op.f('ix_hydro_river_main_riv'), table_name='hydro_river')
    op.drop_index(op.f('ix_hydro_river_hybas_l12'), table_name='hydro_river')
    op.drop_geospatial_index('idx_hydro_river_geom', table_name='hydro_river', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('hydro_river')
    op.drop_index('ix_hydro_basin_level_next_down', table_name='hydro_basin')
    op.drop_geospatial_index('idx_hydro_basin_geom', table_name='hydro_basin', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('hydro_basin')
    # ### end Alembic commands ###
